### ISSUE TITLE
Unexpected await in cli.js

### ISSUE THREAD

**Issue by jrabek** [PhaserEditor2D/phaser-asset-pack-hashing#1]
https://github.com/PhaserEditor2D/phaser-asset-pack-hashing/blob/main/cli.js#L59 is a top level await.  Await must be inside a method marked async.

Ran into this issue when building a typescript based phaser project generated by Phaser Editor 3.15.

**Comment by PhaserEditor2D** [comment]
Hi @jrabek! 

How do you get the error?

The `cli.js` file is part of an NPM package with `module` type: https://github.com/PhaserEditor2D/phaser-asset-pack-hashing/blob/ca2da04c453e3dbed36679000a181401130aa711/package.json#L2

In that case, a top-level await is allowed: https://v8.dev/features/top-level-await

**Comment by jrabek** [comment]
Sorry.  I was using an older version of node when I ran into this.  Can close!
